"""add applicant role

Revision ID: a9d61b0722af
Revises: 1f56d12fae9f
Create Date: 2026-09-01 12:16:16.763023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d61b0722af'
down_revision: Union[str, Sequence[str], None] = '1f56d12fae9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('years_of_experience', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants', 'years_of_experience')
    # ### end Alembic commands ###
